### ISSUE TITLE
Make marathon credentials optional

### ISSUE THREAD

**Issue by ghost** [tendrilinc/marathon-autoscaler#10]
How do i run the autoscaler app where I have a marathon installation without credentials

**Comment by kernelpanek-segfault** [comment]
Good point! I think we should change the username/password flags to be optional.

**Comment by ghost** [comment]
Is there a way i can contribute to this??

**Comment by kernelpanek-segfault** [comment]
@avinashkolluru Thank you for your help on improving the quality of this project!!
