### ISSUE TITLE
problem w/ app name that is a substring of another app name

### ISSUE THREAD

**Issue by kevinwsin** [tendrilinc/marathon-autoscaler#24]
Hi, I ran into a problem where I was testing marathon-autoscaler w/ two Marathon apps, one named "nginx" and the other "nginx-2."  Only the "nginx" app was set with the marathon autoscaler tags and it looks like marathon-autoscaler was skipping over that b/c the label lookup was not working properly (I think due to using `in` instead of `==` in the app name lookups).  I got around it by removing the "nginx-2" app from my Marathon instance.  Thanks.

**Comment by kernelpanek-segfault** [comment]
@kevinwsin Thank you for finding this problem! Once my colleague can review my change and merge the PR, we'll have a new docker image built.

**Comment by kernelpanek-segfault** [comment]
This issue is resolved.
