### ISSUE TITLE
Make datadog optional

### ISSUE THREAD

**Issue by DavidXArnold** [tendrilinc/marathon-autoscaler#4]
Datadog metric reporting should be optional. Please update the autoscaler to run and not report metrics to datadog if datadog api key etc.. is not defined.

**Comment by kernelpanek-segfault** [comment]
@DavidXArnold [this PR](../pull/6) might do the trick.

**Comment by DavidXArnold** [comment]
Resolved in https://github.com/tendrilinc/marathon-autoscaler/pull/6
